version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/webapp-runner-9"
    schedule:
      interval: "monthly"
    ignore:
      - dependency-name: "tomcat.version"
        update-types: ["version-update:semver-major"]
    labels:
      - "skip changelog"
      - "tomcat 9"
      - "dependencies"
    groups:
      tomcat:
        update-types:
          - "minor"
          - "patch"
        patterns:
          - "org.apache.tomcat*:*"
      maven-plugins:
        update-types:
          - "minor"
          - "patch"
        patterns:
          - "org.apache.maven.plugins:*"
      maven-dependencies:
        update-types:
          - "minor"
          - "patch"
        exclude-patterns:
          - "org.apache.tomcat*:*"
          - "org.apache.maven.plugins:*"
  - package-ecosystem: "maven"
    directory: "/webapp-runner-10"
    schedule:
      interval: "monthly"
    ignore:
      - dependency-name: "tomcat.version"
        update-types: ["version-update:semver-major"]
    labels:
      - "skip changelog"
      - "tomcat 10"
      - "dependencies"
    groups:
      tomcat:
        update-types:
          - "minor"
          - "patch"
        patterns:
          - "org.apache.tomcat*:*"
      maven-plugins:
        update-types:
          - "minor"
          - "patch"
        patterns:
          - "org.apache.maven.plugins:*"
      maven-dependencies:
        update-types:
          - "minor"
          - "patch"
        exclude-patterns:
          - "org.apache.tomcat*:*"
          - "org.apache.maven.plugins:*"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    labels:
      - "skip changelog"
      - "dependencies"
    groups:
      github-actions:
        update-types:
          - "minor"
          - "patch"
